# Generated by Django 2.1.1 on 2018-09-09 22:13

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

	dependencies = [
		("djpaypal", "0004_auto_20180323_2137"),
	]

	operations = [
		migrations.AlterField(
			model_name="billingagreement",
			name="override_charge_mode",
			field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
		),
		migrations.AlterField(
			model_name="billingagreement",
			name="override_merchant_preferences",
			field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
		),
	]
